# Generated by Django 5.0.1 on 2024-02-14 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTEnt', '0002_avatarimagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='zapatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=50)),
                ('fecha_entrega', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='AvatarImagen',
            new_name='Avatar',
        ),
    ]
