# Generated by Django 5.0.1 on 2024-02-14 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTEnt', '0003_zapatos_rename_avatarimagen_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='zapatos',
        ),
    ]
